[client]
showSidebarNavigation = false

[server]
headless = true
maxUploadSize = 50
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
