[client]
showSidebarNavigation = false

[server]
headless = true
maxUploadSize = 10
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
base = "dark"
